# Generated by Django 3.1.4 on 2021-12-14 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificacao', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificacao',
            old_name='date',
            new_name='data_not',
        ),
        migrations.RemoveField(
            model_name='notificacao',
            name='url',
        ),
    ]
