# Generated by Django 3.1.4 on 2021-12-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacao', '0003_auto_20211223_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='n_created_at2',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='n_updated_at2',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
