# Generated by Django 3.1.4 on 2021-12-27 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacao', '0006_auto_20211226_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='link_name',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
    ]
