# Generated by Django 3.1.4 on 2021-12-27 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacao', '0007_notificacao_link_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='notificacao_alert',
            field=models.CharField(blank=True, choices=[(1, '<django.db.models.fields.related.ForeignKey> assinou-te a ti'), (2, '<django.db.models.fields.related.ForeignKey> enviou-te mensagem'), (3, '<django.db.models.fields.related.ForeignKey> comentou na tua foto de perfil'), (4, '<django.db.models.fields.related.ForeignKey> reagiu na tua foto de perfil'), (5, '<django.db.models.fields.related.ForeignKey> reagiu a um comentario na tua foto de perfil'), (6, '<django.db.models.fields.related.ForeignKey> respondeu a um comentario na tua foto de perfil'), (7, '<django.db.models.fields.related.ForeignKey> reagiu na tua publicação'), (8, '<django.db.models.fields.related.ForeignKey> reagiu a um comentario na tua publicação'), (9, '<django.db.models.fields.related.ForeignKey> respondeu a um comentario na tua publicação'), (10, '<django.db.models.fields.related.ForeignKey> comentou na tua publicação'), (11, '<django.db.models.fields.related.ForeignKey> deixou de ser teu assinante')], max_length=240, null=True),
        ),
    ]
