# Generated by Django 3.1.4 on 2021-11-09 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postes', '0002_auto_20211110_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poste',
            name='Texto',
            field=models.CharField(default=1, max_length=261),
            preserve_default=False,
        ),
    ]
