# Generated by Django 3.1.4 on 2021-11-11 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postes', '0003_auto_20211110_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poste',
            name='Foto',
            field=models.ImageField(blank=True, default='Vf/default.png', upload_to='Foto/'),
        ),
        migrations.AlterField(
            model_name='poste',
            name='Texto',
            field=models.CharField(blank=True, max_length=261),
        ),
        migrations.AlterField(
            model_name='poste',
            name='Video',
            field=models.FileField(blank=True, default='Vf/default.png', upload_to='Video/'),
        ),
    ]
