# Generated by Django 3.1.4 on 2021-11-11 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postes', '0005_auto_20211111_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poste',
            name='Foto',
            field=models.ImageField(blank=True, null=True, upload_to='Foto/'),
        ),
        migrations.AlterField(
            model_name='poste',
            name='Video',
            field=models.FileField(blank=True, null=True, upload_to='Video/'),
        ),
    ]
