# Generated by Django 3.1.4 on 2021-11-11 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postes', '0006_auto_20211111_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poste',
            name='Foto1',
        ),
        migrations.RemoveField(
            model_name='poste',
            name='Video2',
        ),
    ]
