# Generated by Django 3.1.4 on 2021-11-11 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postes', '0007_auto_20211111_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poste',
            name='Texto',
            field=models.CharField(blank=True, max_length=261, null=True),
        ),
    ]
