# Generated by Django 3.1.4 on 2021-12-11 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postes', '0009_auto_20211122_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poste',
            name='id',
        ),
        migrations.AddField(
            model_name='poste',
            name='poste_id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False),
        ),
    ]
