# Generated by Django 3.1.4 on 2021-12-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postes', '0010_auto_20211211_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poste',
            name='poste_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
