# Generated by Django 3.1.4 on 2021-12-13 08:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('postes', '0011_auto_20211211_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='poste',
            name='p_braco_forca',
            field=models.ManyToManyField(blank=True, related_name='p_braco_forca', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='poste',
            name='p_cara_coracao',
            field=models.ManyToManyField(blank=True, related_name='p_cara_coracao', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='poste',
            name='p_cara_dinheiro',
            field=models.ManyToManyField(blank=True, related_name='p_cara_dinheiro', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='poste',
            name='p_cara_surridente',
            field=models.ManyToManyField(blank=True, related_name='p_cara_surridente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='poste',
            name='p_cara_triste',
            field=models.ManyToManyField(blank=True, related_name='p_cara_triste', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='poste',
            name='p_nao_gosto',
            field=models.ManyToManyField(blank=True, related_name='p_nao_gosto', to=settings.AUTH_USER_MODEL),
        ),
    ]
