# Generated by Django 3.1.4 on 2021-11-16 03:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('postes', '0008_auto_20211111_0929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C_Texto', models.CharField(blank=True, max_length=261, null=True)),
                ('C_Foto', models.ImageField(blank=True, null=True, upload_to='CFoto/')),
                ('C_Video', models.FileField(blank=True, null=True, upload_to='CVideo/')),
                ('active', models.BooleanField(default=True)),
                ('c_created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('c_updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_comments', to=settings.AUTH_USER_MODEL)),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='postes.poste')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_reply', to='comentarios.comment')),
            ],
            options={
                'ordering': ('c_created_at',),
            },
        ),
    ]
