# Generated by Django 3.1.4 on 2021-12-11 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postes', '0010_auto_20211211_1001'),
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='id',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='poste',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='poste_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Poste_id', to='postes.poste'),
            preserve_default=False,
        ),
    ]
