# Generated by Django 3.1.4 on 2021-12-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0002_auto_20211211_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
