# Generated by Django 3.1.4 on 2021-12-13 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('postes', '0011_auto_20211211_1423'),
        ('comentarios', '0004_auto_20211211_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='CComment',
            fields=[
                ('ccomment_id', models.AutoField(primary_key=True, serialize=False)),
                ('cC_Texto', models.CharField(blank=True, max_length=261, null=True)),
                ('cC_Foto', models.ImageField(blank=True, null=True, upload_to='CFoto/')),
                ('cC_Video', models.FileField(blank=True, null=True, upload_to='CVideo/')),
                ('cactive', models.BooleanField(default=True)),
                ('cc_created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('cc_updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('ccommenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cposted_comments', to=settings.AUTH_USER_MODEL)),
                ('cposte_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cPoste_id', to='postes.poste')),
                ('creply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ccomment_reply', to='comentarios.ccomment')),
            ],
            options={
                'ordering': ('cc_created_at',),
            },
        ),
    ]
