# Generated by Django 3.1.4 on 2021-12-13 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postes', '0011_auto_20211211_1423'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comentarios', '0005_ccomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment2',
            fields=[
                ('comment_id2', models.AutoField(primary_key=True, serialize=False)),
                ('C_Texto2', models.CharField(blank=True, max_length=261, null=True)),
                ('C_Foto2', models.ImageField(blank=True, null=True, upload_to='CFoto/')),
                ('C_Video2', models.FileField(blank=True, null=True, upload_to='CVideo/')),
                ('active2', models.BooleanField(default=True)),
                ('c_created_at2', models.DateTimeField(auto_now_add=True, null=True)),
                ('c_updated_at2', models.DateTimeField(auto_now=True, null=True)),
                ('commenter2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_comments2', to=settings.AUTH_USER_MODEL)),
                ('poste_id2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Poste_id2', to='postes.poste')),
                ('reply2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_reply2', to='comentarios.comment2')),
            ],
            options={
                'ordering': ('c_created_at2',),
            },
        ),
        migrations.DeleteModel(
            name='CComment',
        ),
    ]
