# Generated by Django 3.1.4 on 2021-12-13 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0006_auto_20211213_0711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment2',
            name='poste_id2',
        ),
        migrations.AddField(
            model_name='comment2',
            name='comment_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Comment_id', to='comentarios.comment'),
            preserve_default=False,
        ),
    ]
