# Generated by Django 3.1.4 on 2021-11-07 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caixa', models.TextField(blank=True, max_length=1000)),
                ('m_created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('m_updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('rec_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('m_created_at',),
            },
        ),
    ]
