# Generated by Django 3.1.4 on 2021-11-07 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Apelido', models.CharField(blank=True, max_length=160, null=True)),
                ('Bio', models.CharField(blank=True, max_length=160, null=True)),
                ('Genero', models.CharField(blank=True, choices=[('Lésbica', 'Lésbica'), ('Gay', 'Gay'), ('Bisexual', 'Bisexual'), ('Transexual', 'Transexual'), ('Feminino', 'Feminino'), ('Masculino', 'Masculino')], max_length=13, null=True)),
                ('Interesse', models.CharField(blank=True, choices=[('Lésbica', 'Lésbica'), ('Gay', 'Gay'), ('Bisexual', 'Bisexual'), ('Transexual', 'Transexual'), ('Feminino', 'Feminino'), ('Masculino', 'Masculino')], max_length=13, null=True)),
                ('Data_de_Nascimento', models.DateTimeField(blank=True, null=True)),
                ('Nacionalidade', models.CharField(blank=True, max_length=54, null=True)),
                ('Residencia', models.CharField(blank=True, max_length=54, null=True)),
                ('p_created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('p_updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('Usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('followers', models.ManyToManyField(blank=True, related_name='followers_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
