# Generated by Django 3.1.4 on 2021-11-07 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='Apelido',
        ),
    ]
