# Generated by Django 3.1.4 on 2021-11-07 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo_foto', models.CharField(blank=True, max_length=60, null=True)),
                ('Nome_foto', models.CharField(blank=True, max_length=60, null=True)),
                ('File_foto', models.ImageField(blank=True, default='Foto/default.png', upload_to='Foto/')),
                ('f_created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('f_updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('User_foto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
