# Generated by Django 3.1.4 on 2021-11-09 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foto_de_perfil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='File_foto',
            field=models.ImageField(blank=True, default='Foto/default.png', upload_to='Foto_de_perfil/'),
        ),
    ]
